/**********************************************************************
ESP32 COMMAND STATION

COPYRIGHT (c) 2022 Mike Dunston

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see http://www.gnu.org/licenses
**********************************************************************/

#ifndef HARDWARE_PINMAP_CSPCB_HXX_
#define HARDWARE_PINMAP_CSPCB_HXX_

#include "sdkconfig.h"

#undef CONFIG_DCC_TRACK_SIGNAL_PIN
#undef CONFIG_OPS_HBRIDGE_L298
#undef CONFIG_OPS_HBRIDGE_LMD18200
#undef CONFIG_OPS_HBRIDGE_DRV880X
#undef CONFIG_OPS_HBRIDGE_DRV8873
#undef CONFIG_OPS_HBRIDGE_DRV8873_5A
#undef CONFIG_OPS_HBRIDGE_POLOLU
#undef CONFIG_OPS_HBRIDGE_BTS7960B_5A
#undef CONFIG_OPS_HBRIDGE_BTS7960B_10A
#undef CONFIG_RAILCOM_TRIGGER_PIN
#undef CONFIG_RAILCOM_DATA_PIN
#undef CONFIG_RAILCOM_DIRECTION_PIN
#undef CONFIG_RAILCOM_SHORT_PIN
#undef CONFIG_OLED_RESET_PIN
#undef CONFIG_PROG_TRACK_ENABLE_PIN
#undef CONFIG_RAILCOM_CUT_OUT_ENABLED
#undef CONFIG_RAILCOM_DATA_ENABLED
#undef CONFIG_I2C_SCL_PIN
#undef CONFIG_I2C_SDA_PIN
#undef CONFIG_I2C_ADC_ALERT_PIN
#undef CONFIG_STATUS_LED_DATA_PIN
#undef CONFIG_STATUS_LED_WIFI_STA_PIN
#undef CONFIG_STATUS_LED_WIFI_AP_PIN
#undef CONFIG_STATUS_LED_BOOTLOADER_ACTIVE_PIN
#undef CONFIG_STATUS_LED_OPS_ACTIVE_PIN
#undef CONFIG_STATUS_LED_PROG_ACTIVE_PIN
#undef CONFIG_OLED_RESET_PIN
#undef CONFIG_FACTORY_RESET_PIN
#undef CONFIG_BOOTLOADER_PIN
#undef CONFIG_OLCB_TWAI_RX_PIN
#undef CONFIG_OLCB_TWAI_TX_PIN
#undef CONFIG_OPSTRACK_ADC_CHANNEL_0
#undef CONFIG_OPSTRACK_ADC_CHANNEL_1
#undef CONFIG_OPSTRACK_ADC_CHANNEL_2
#undef CONFIG_OPSTRACK_ADC_CHANNEL_3
#undef CONFIG_OPSTRACK_ADC_CHANNEL_4
#undef CONFIG_OPSTRACK_ADC_CHANNEL_5
#undef CONFIG_OPSTRACK_ADC_CHANNEL_6
#undef CONFIG_OPSTRACK_ADC_CHANNEL_7
#undef CONFIG_OPSTRACK_ADC_CHANNEL_8
#undef CONFIG_OPSTRACK_ADC_CHANNEL_9
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_0
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_1
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_2
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_3
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_4
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_5
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_6
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_7
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_8
#undef CONFIG_OPSTRACK_ADC2_CHANNEL_9
#undef CONFIG_OPSTRACK_ADC_I2C_CHANNEL_1
#undef CONFIG_OPSTRACK_ADC_I2C_CHANNEL_2
#undef CONFIG_OPSTRACK_ADC_I2C_CHANNEL_3
#undef CONFIG_PROGTRACK_ADC_CHANNEL_0
#undef CONFIG_PROGTRACK_ADC_CHANNEL_1
#undef CONFIG_PROGTRACK_ADC_CHANNEL_2
#undef CONFIG_PROGTRACK_ADC_CHANNEL_3
#undef CONFIG_PROGTRACK_ADC_CHANNEL_4
#undef CONFIG_PROGTRACK_ADC_CHANNEL_5
#undef CONFIG_PROGTRACK_ADC_CHANNEL_6
#undef CONFIG_PROGTRACK_ADC_CHANNEL_7
#undef CONFIG_PROGTRACK_ADC_CHANNEL_8
#undef CONFIG_PROGTRACK_ADC_CHANNEL_9
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_0
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_1
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_2
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_3
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_4
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_5
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_6
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_7
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_8
#undef CONFIG_PROGTRACK_ADC2_CHANNEL_9
#undef CONFIG_PROGTRACK_ADC_I2C_CHANNEL_1
#undef CONFIG_PROGTRACK_ADC_I2C_CHANNEL_2
#undef CONFIG_PROGTRACK_ADC_I2C_CHANNEL_3

#undef CONFIG_OPS_DCC_PREAMBLE_BITS
#undef CONFIG_PROG_DCC_PREAMBLE_BITS

#define CONFIG_RAILCOM_CUT_OUT_ENABLED 1

#if CONFIG_IDF_TARGET_ESP32
  // RailCom is only supported on the ESP32 (for now)
  #define CONFIG_RAILCOM_DATA_ENABLED 1
#endif // CONFIG_IDF_TARGET_ESP32

#define CONFIG_OPS_DCC_PREAMBLE_BITS 16
#define CONFIG_PROG_DCC_PREAMBLE_BITS 22

#if CONFIG_ESP32CS_PCB_V150
  #define CONFIG_DCC_TRACK_SIGNAL_PIN 16

  #define CONFIG_OPS_HBRIDGE_DRV8873_5A 1

  #define CONFIG_OPS_TRACK_ENABLE_PIN 17

  #define CONFIG_OPSTRACK_ADC_CHANNEL_0 1

  #define CONFIG_PROG_HBRIDGE_DRV880X 1

  #define CONFIG_PROG_TRACK_ENABLE_PIN 18

  #define CONFIG_PROGTRACK_ADC_CHANNEL_3 1

  #define CONFIG_RAILCOM_TRIGGER_PIN 12
  #define CONFIG_RAILCOM_DATA_PIN 26
  #define CONFIG_RAILCOM_DIRECTION_PIN 25

  #define CONFIG_OLED_RESET_PIN 0

  #define CONFIG_FACTORY_RESET_PIN 32
  #define CONFIG_BOOTLOADER_PIN 33

  #define CONFIG_OLCB_TWAI_RX_PIN 4
  #define CONFIG_OLCB_TWAI_TX_PIN 5

  #define CONFIG_I2C_SCL_PIN 21
  #define CONFIG_I2C_SDA_PIN 23

  #define CONFIG_STATUS_LED_DATA_PIN 22

  #define CONFIG_TEMPSENSOR_ADC_CHANNEL_7 1
#elif CONFIG_ESP32CS_PCB_V100

  #define CONFIG_DCC_TRACK_SIGNAL_PIN 17

  #define CONFIG_OPS_HBRIDGE_LMD18200 1

  #define CONFIG_OPS_TRACK_ENABLE_PIN 4

  #define CONFIG_OPSTRACK_ADC_CHANNEL_0 1

  #define CONFIG_DCC_TRACK_BRAKE_PIN 26

  #define CONFIG_PROG_HBRIDGE_L298 1

  #define CONFIG_PROG_TRACK_ENABLE_PIN 18

  #define CONFIG_PROGTRACK_ADC_CHANNEL_3 1

  #define CONFIG_RAILCOM_TRIGGER_PIN 12
  #define CONFIG_RAILCOM_DATA_PIN 33
  #define CONFIG_RAILCOM_DIRECTION_PIN 25

  #define CONFIG_OLED_RESET_PIN -1      

  #define CONFIG_FACTORY_RESET_PIN 34
  #define CONFIG_BOOTLOADER_PIN -1

  #define CONFIG_OLCB_TWAI_RX_PIN 27
  #define CONFIG_OLCB_TWAI_TX_PIN 32

  #define CONFIG_I2C_SCL_PIN 21
  #define CONFIG_I2C_SDA_PIN 23

  #define CONFIG_STATUS_LED_DATA_PIN 22

  #define CONFIG_TEMPSENSOR_ADC_CHANNEL_7 1
#elif CONFIG_ESP32CS_PCB_V200
    #define CONFIG_DCC_TRACK_SIGNAL_PIN 10

    #define CONFIG_DCC_OLCB_ENABLE_PIN 12

    #define CONFIG_OPS_HBRIDGE_DRV8873_5A 1

    #define CONFIG_OPS_TRACK_ENABLE_PIN 34

    #define CONFIG_OPSTRACK_ADC_I2C_CHANNEL_1 1

    #define CONFIG_PROG_HBRIDGE_DRV880X 1

    #define CONFIG_PROG_TRACK_ENABLE_PIN 33

    #define CONFIG_PROGTRACK_ADC_I2C_CHANNEL_2 1

    #define CONFIG_RAILCOM_TRIGGER_PIN 21
    #define CONFIG_RAILCOM_DATA_PIN 47
    #define CONFIG_RAILCOM_DIRECTION_PIN 48
    #define CONFIG_RAILCOM_SHORT_PIN 45

    #define CONFIG_I2C_SCL_PIN 18

    #define CONFIG_I2C_SDA_PIN 8

    #define CONFIG_I2C_ADC_ALERT_PIN 46

    #define CONFIG_STATUS_LED_WIFI_STA_PIN 15
    #define CONFIG_STATUS_LED_WIFI_AP_PIN 7
    #define CONFIG_STATUS_LED_BOOTLOADER_ACTIVE_PIN 6
    #define CONFIG_STATUS_LED_OPS_ACTIVE_PIN 5
    #define CONFIG_STATUS_LED_PROG_ACTIVE_PIN 4

    #define CONFIG_OLED_RESET_PIN 3

    #define CONFIG_FACTORY_RESET_PIN 2
    #define CONFIG_BOOTLOADER_PIN 1

    #define CONFIG_OLCB_TWAI_RX_PIN 16
    #define CONFIG_OLCB_TWAI_TX_PIN 17

    #define CONFIG_TEMPSENSOR_ADC2_CHANNEL_2 1
#endif // PCB Version

#endif // HARDWARE_PINMAP_CSPCB_HXX_